module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#fffbff",
        "surface-container-highest": "#e5e2db",
        "on-error-container": "#93000a",
        "on-primary-container": "#799dd6",
        "surface-variant": "#e5e2db",
        "outline-variant": "#c3c6d1",
        "surface-container-low": "#f6f3ec",
        "tertiary": "#695f00",
        "primary-fixed": "#d5e3ff",
        "on-background": "#1c1c18",
        "inverse-primary": "#a7c8ff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3f0ea",
        "on-tertiary-container": "#474000",
        "primary-container": "#003366",
        "tertiary-fixed": "#f9e534",
        "tertiary-container": "#bead00",
        "outline": "#737780",
        "secondary-fixed": "#ffdad4",
        "on-surface": "#1c1c18",
        "secondary-container": "#e41f13",
        "on-tertiary-fixed-variant": "#4f4800",
        "secondary-fixed-dim": "#ffb4a8",
        "error": "#ba1a1a",
        "surface-tint": "#3a5f94",
        "on-surface-variant": "#43474f",
        "tertiary-fixed-dim": "#dbc90a",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#1f477b",
        "on-tertiary": "#ffffff",
        "surface": "#fcf9f2",
        "surface-bright": "#fcf9f2",
        "background": "#fcf9f2",
        "surface-container": "#f0eee7",
        "on-secondary-fixed": "#410000",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001b3c",
        "on-secondary": "#ffffff",
        "secondary": "#bc0000",
        "primary": "#001e40",
        "on-secondary-fixed-variant": "#930000",
        "surface-container-high": "#ebe8e1",
        "inverse-surface": "#31312c",
        "on-tertiary-fixed": "#201c00",
        "on-primary": "#ffffff",
        "surface-dim": "#dcdad3",
        "primary-fixed-dim": "#a7c8ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "baseline": "24px",
        "rule-height": "24px",
        "gutter": "1.5rem",
        "margin-edge": "2rem"
      },
      fontFamily: {
        "body-lg": ["Gochi Hand"],
        "headline-lg": ["Bricolage Grotesque"],
        "label-sm": ["Space Mono"],
        "headline-lg-mobile": ["Bricolage Grotesque"],
        "headline-xl": ["Bricolage Grotesque"],
        "body-md": ["Gochi Hand"]
      },
      fontSize: {
        "body-lg": ["20px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "fontWeight": "800" }],
        "body-md": ["18px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
};
