config:
  aws:region: us-east-1
  dopamint:environment: dev
  dopamint:domain: dev.dopamint.example.com
  dopamint:db-instance-class: db.r6g.large
  dopamint:db-min-capacity: 0.5
  dopamint:db-max-capacity: 4
  dopamint:db-serverless: "true"
  dopamint:cache-node-type: cache.t4g.medium
  dopamint:benchmark-instance-type: c7i.2xlarge
  dopamint:benchmark-min-size: 0
  dopamint:benchmark-max-size: 2
  dopamint:route53-zone-id: ""
