// @generated by sui-tunnel-ts/src/core/sig-vectors.gen.ts — DO NOT EDIT BY HAND.
// Regenerate: (cd sui-tunnel-ts && node --import tsx src/core/sig-vectors.gen.ts)
//
// Reproducible signature fixtures over the canonical wire-format messages,
// consumed by sui_tunnel::signature_vectors_tests. Fixed deterministic keys.
#[test_only]
module sui_tunnel::sig_vectors;

// --- ed25519 party public keys (secrets 0x01..0x20 / 0x21..0x40) ---
public fun ed25519_pk_a(): vector<u8> {
    x"79b5562e8fe654f94078b112e8a98ba7901f853ae695bed7e0e3910bad049664"
}

public fun ed25519_pk_b(): vector<u8> {
    x"e7f162a10bec559afea195e4dce84b69568d5d2cb0963eb446c0685e2b17f2f0"
}

// ed25519 over state_update
public fun ed25519_state_update_sig_a(): vector<u8> {
    x"6941c8ba5bd00d2695d5edd6d33e3fb3e46a83685e09717382b0b0b82246726323a6abc9bec1ebb8535bb3100a03bf5205e7ce5c898f8d071916c4c795ac180b"
}

public fun ed25519_state_update_sig_b(): vector<u8> {
    x"3ee65d80264ea3e9e780937916c9815de8a4ce7ac162eef0ab2c65fbe272fc52564fac381dc1db49814a055e53ca2ab63e04f1b4d1154424ac9246c9f6f5440c"
}

// ed25519 over settlement
public fun ed25519_settlement_sig_a(): vector<u8> {
    x"7841abb9e22521b7c61af43ede5423cb3c7f72eeb16f5c6aa880067388968663ef0111363fa5f799c18d7928334cffc8be918c0f5bf9a1af8bf3a668d3d13602"
}

public fun ed25519_settlement_sig_b(): vector<u8> {
    x"90df4242d55dba3486f6c1fcfde36f1d952ff2096bd57593829293e05d7b94445b13622964cfb3d1ab141d2276473cad72e1a1840a8652fde817fad1250f8606"
}

// ed25519 over settlement_v2
public fun ed25519_settlement_v2_sig_a(): vector<u8> {
    x"3518e7a913477ffbb01fbdf1c61a7c26da09cc40017463a6673a4d5cdd9d0bd453585de5e0944b3b1c3ddbfd6ccac8d7b5eac9ec339786fada851fa13ae04f04"
}

public fun ed25519_settlement_v2_sig_b(): vector<u8> {
    x"5199e9fab06e48e36680815c97144e167b79f662a9e6d1c8bd45ca6e8b4c2a7425908b00f1ae7ed808ccaa4c653e1c6c427209a2484fa39bd5dfa33ac7bf9c05"
}

// ed25519 over htlc_lock
public fun ed25519_htlc_lock_sig_a(): vector<u8> {
    x"c2690d9397355b88a2527584ea7fa8ed271394b08ec29fd975ff04e9f418565c2db98c9148d226584c8101adc535b04e8c6c1cc6571add60116b084fe525ac05"
}

public fun ed25519_htlc_lock_sig_b(): vector<u8> {
    x"77020031995b61e8071a10706667a491c2d55dbbfc20454a75f67ed9fa4cc34291428f402311390349cd02cdf771605faaa16dc6629d9546e6c31fafd46e9806"
}

// --- secp256k1: pk (33B compressed) + sig (64B, low-s) over SHA256(state_update) ---
public fun secp256k1_pk(): vector<u8> {
    x"0284bf7562262bbd6940085748f3be6afa52ae317155181ece31b66351ccffa4b0"
}

public fun secp256k1_state_update_sig(): vector<u8> {
    x"b3adb20a74f777682f0319ae8052180373a5e750b19e51c1c57d4768de547e56688ac83253bacfb2981d1c8f5e822e2e805887ebb7e4162035c5e90b9a34a855"
}
