// Generator: emits reproducible signature test vectors for the Move test suite.
//
//   node --import tsx src/core/sig-vectors.gen.ts
//
// It signs the four canonical wire-format messages (state_update, settlement,
// settlement_v2, htlc_lock) with FIXED deterministic keys and writes a Move
// `#[test_only]` fixture module to `sui_tunnel/tests/sig_vectors.move`. The Move
// test `signature_vectors_tests.move` rebuilds each message with the on-chain
// serializers and asserts `signature::verify(scheme, pk, msg, sig)` accepts the
// off-chain signatures — proving SDK-signed payloads settle on-chain.
//
// Canonical inputs match wire_format_tests.move / golden.gen.ts exactly:
//   tunnel_id=@0xab  state_hash/payment_hash=0x01..0x20
//   state_update: nonce=42 ts=1234567890 balA=1000 balB=2000
//   settlement:   balA=1000 balB=2000 final_nonce=43 ts=1234567890
//   htlc_lock:    amount=500 sender=@0xaa receiver=@0xbb expiry=9999999
//
// ed25519 secrets: A=0x01..0x20, B=0x21..0x40 (same as golden.gen.ts).
//
// IF YOU CHANGE THE WIRE FORMAT, regenerate this and update the Move tests in
// lockstep, or on-chain verification of off-chain signatures will silently fail.
import { bls12_381 } from "@noble/curves/bls12-381.js";
import { secp256k1 } from "@noble/curves/secp256k1.js";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { toHex } from "./bytes";
import { keyPairFromSecret, sign, verify } from "./crypto";
import {
  serializeHtlcLock,
  serializeSettlement,
  serializeSettlementWithRoot,
  serializeStateUpdate,
} from "./wire";

// --- canonical inputs (shared with wire_format_tests.move) ---
const TUNNEL_ID = "0xab";
const hash32 = Uint8Array.from({ length: 32 }, (_, i) => i + 1); // 0x01..0x20

const messages: Record<string, Uint8Array> = {
  state_update: serializeStateUpdate({
    tunnelId: TUNNEL_ID,
    stateHash: hash32,
    nonce: 42n,
    timestamp: 1234567890n,
    partyABalance: 1000n,
    partyBBalance: 2000n,
  }),
  settlement: serializeSettlement({
    tunnelId: TUNNEL_ID,
    partyABalance: 1000n,
    partyBBalance: 2000n,
    finalNonce: 43n,
    timestamp: 1234567890n,
  }),
  settlement_v2: serializeSettlementWithRoot({
    tunnelId: TUNNEL_ID,
    partyABalance: 1000n,
    partyBBalance: 2000n,
    finalNonce: 43n,
    timestamp: 1234567890n,
    transcriptRoot: hash32,
  }),
  htlc_lock: serializeHtlcLock({
    tunnelId: TUNNEL_ID,
    paymentHash: hash32,
    amount: 500n,
    sender: "0xaa",
    receiver: "0xbb",
    expiryMs: 9999999n,
  }),
};

// --- fixed ed25519 keypairs ---
const secretA = Uint8Array.from({ length: 32 }, (_, i) => i + 1); // 0x01..0x20
const secretB = Uint8Array.from({ length: 32 }, (_, i) => i + 33); // 0x21..0x40
const kpA = keyPairFromSecret(secretA);
const kpB = keyPairFromSecret(secretB);

const out: string[] = [];
const fn = (name: string, bytes: Uint8Array) =>
  out.push(`public fun ${name}(): vector<u8> { x"${toHex(bytes)}" }`);

out.push(
  "// @generated by sui-tunnel-ts/src/core/sig-vectors.gen.ts — DO NOT EDIT BY HAND.",
);
out.push(
  "// Regenerate: (cd sui-tunnel-ts && node --import tsx src/core/sig-vectors.gen.ts)",
);
out.push("//");
out.push(
  "// Reproducible signature fixtures over the canonical wire-format messages,",
);
out.push(
  "// consumed by sui_tunnel::signature_vectors_tests. Fixed deterministic keys.",
);
out.push("#[test_only]");
out.push("module sui_tunnel::sig_vectors;");
out.push("");
out.push(
  "// --- ed25519 party public keys (secrets 0x01..0x20 / 0x21..0x40) ---",
);
fn("ed25519_pk_a", kpA.publicKey);
fn("ed25519_pk_b", kpB.publicKey);
out.push("");

// ed25519: both parties sign every message (RFC 8032 deterministic).
for (const [name, msg] of Object.entries(messages)) {
  const sigA = sign(msg, kpA.secretKey);
  const sigB = sign(msg, kpB.secretKey);
  if (!verify(sigA, msg, kpA.publicKey) || !verify(sigB, msg, kpB.publicKey)) {
    throw new Error(`ed25519 self-verify failed for ${name}`);
  }
  out.push(`// ed25519 over ${name}`);
  fn(`ed25519_${name}_sig_a`, sigA);
  fn(`ed25519_${name}_sig_b`, sigB);
  out.push("");
}

// --- secp256k1 (scheme 3): Sui verifies ECDSA over SHA256(msg), low-s, 33B pk ---
const schemesGenerated: string[] = ["ed25519"];
try {
  const skSecp = Uint8Array.from({ length: 32 }, (_, i) => i + 1);
  const pkSecp: Uint8Array = secp256k1.getPublicKey(skSecp, true); // compressed 33B
  const msg = messages.state_update;
  const digest = new Uint8Array(createHash("sha256").update(msg).digest());
  const sigRaw: any = secp256k1.sign(digest, skSecp, {
    prehash: false,
    lowS: true,
  });
  const sigSecp: Uint8Array =
    sigRaw instanceof Uint8Array
      ? sigRaw
      : (sigRaw.toBytes?.("compact") ?? sigRaw.toCompactRawBytes?.());
  if (sigSecp.length !== 64)
    throw new Error(`secp256k1 sig len ${sigSecp.length} != 64`);
  if (
    !secp256k1.verify(sigSecp, digest, pkSecp, { prehash: false, lowS: true })
  ) {
    throw new Error("secp256k1 self-verify failed");
  }
  out.push(
    "// --- secp256k1: pk (33B compressed) + sig (64B, low-s) over SHA256(state_update) ---",
  );
  fn("secp256k1_pk", pkSecp);
  fn("secp256k1_state_update_sig", sigSecp);
  out.push("");
  schemesGenerated.push("secp256k1");
} catch (e) {
  console.warn("secp256k1 vectors skipped:", (e as Error).message);
}

// --- bls12381 min_sig (scheme 1): pk G2 (96B), sig G1 (48B) ---
try {
  const short: any = bls12_381.shortSignatures;
  const skBls = Uint8Array.from({ length: 32 }, (_, i) => i + 1);
  const msg = messages.state_update;
  const toBytes = (p: any): Uint8Array =>
    p instanceof Uint8Array ? p : (p.toBytes?.() ?? p.toRawBytes?.());
  const pk = toBytes(short.getPublicKey(skBls));
  const sig = toBytes(short.sign(msg, skBls));
  if (pk.length !== 96 || sig.length !== 48) {
    throw new Error(
      `min_sig sizes pk=${pk.length} sig=${sig.length} (want 96/48)`,
    );
  }
  out.push(
    "// --- bls12381 min_sig: pk G2 (96B) + sig G1 (48B) over state_update ---",
  );
  fn("bls_min_sig_pk", pk);
  fn("bls_min_sig_state_update_sig", sig);
  out.push("");
  schemesGenerated.push("bls_min_sig");
} catch (e) {
  console.warn("bls min_sig vectors skipped:", (e as Error).message);
}

// --- bls12381 min_pk (scheme 2): pk G1 (48B), sig G2 (96B) ---
try {
  const long: any = bls12_381.longSignatures;
  const skBls = Uint8Array.from({ length: 32 }, (_, i) => i + 1);
  const msg = messages.state_update;
  const toBytes = (p: any): Uint8Array =>
    p instanceof Uint8Array ? p : (p.toBytes?.() ?? p.toRawBytes?.());
  const pk = toBytes(long.getPublicKey(skBls));
  const sig = toBytes(long.sign(msg, skBls));
  if (pk.length !== 48 || sig.length !== 96) {
    throw new Error(
      `min_pk sizes pk=${pk.length} sig=${sig.length} (want 48/96)`,
    );
  }
  out.push(
    "// --- bls12381 min_pk: pk G1 (48B) + sig G2 (96B) over state_update ---",
  );
  fn("bls_min_pk_pk", pk);
  fn("bls_min_pk_state_update_sig", sig);
  out.push("");
  schemesGenerated.push("bls_min_pk");
} catch (e) {
  console.warn("bls min_pk vectors skipped:", (e as Error).message);
}

const dest = new URL(
  "../../../sui_tunnel/tests/sig_vectors.move",
  import.meta.url,
);
writeFileSync(dest, out.join("\n") + "\n");
console.log(`wrote ${dest.pathname}`);
console.log("schemes generated:", schemesGenerated.join(", "));
